FROM python:3.7-slim-buster

COPY src/ /app
COPY requirements.txt /app

RUN pip install -r app/requirements.txt

WORKDIR "app"

CMD ["uvicorn", "roster_api:app", "--reload", "--proxy-headers", "--host", "0.0.0.0"]